### ISSUE TITLE
feat(http): Support many types of body on Request/Response and all ConnectionBackend implementations

### ISSUE THREAD

**Issue by robwormald** [angular/http#75]
_From @jeffbcross on July 1, 2015 0:24_

These types should be supported by all backends, as much as each backend is technically capable of supporting:

 * FormData (for request only)
 * Blob
 * Document (for response only)
 * Text (String)
 * JSON

TBD: ArrayBufferView/ArrayBuffer?

All expected response types should be able to be explicitly declared on the `Request`, so that they can be optimized by the underlying primitive (see #2609). Request body types won't be explicitly declared.

_Copied from original issue: angular/angular#2803_

**Comment by karayv** [comment]
Any workarounds for FormData? I need to upload file. Thank you.

**Comment by cassand** [comment]
Here are some ideas for the implementation of buffer type :

* Use an enumeration for the response type so developers can benefit from IDE autocompletion.

* Buffer type is declared on the Request with an attribute "buffer" (not "responseType" to not conflict with [Fetch Api ResponseType](https://fetch.spec.whatwg.org/#responsetype) )

Syntax Example : 
```
var options = new RequestOptions({
            	  buffer: ResponseBuffer.ArrayBuffer
 	          });

this.http
	.get("http://example.com/arraybuffer", options)
	.subscribe(res => this.data = res.arraybuffer());
```
Expose a Body interface which could be implemented by the request as well as the response and which follow
https://fetch.spec.whatwg.org/#body

Request : 
https://github.com/angular/angular/pull/7310

Response :
https://github.com/angular/angular/pull/7260

Here are some conflicts between actual implementation and Fetch Api :

* Consume body should return a promise, whereas it return directly the response.
Use a promise can also solve (https://github.com/angular/http/issues/79) but will imply a different syntax (nested promises)

* The Fecth Api expect request to return a ByteStream, whereas browser return a [typed buffer ](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response).
With no "responseType" the browser will use a DOMString and converting a DOMString to an ArrayBuffer could lead to unexpected behavior.

**Comment by templth** [comment]
I implemented a support a `FormData` in requests in the PR #7310. Feel free to make more you comment.

Here is a sample of use:

    let blob = new Blob(['body { color: red; }'], { type: 'text/css' });

    let form = new FormData();
    form.append('test1', 'val1');
    form.append('test2', 123456);
    form.append("userfile", blob);

    return this.http.post('https://contactsapi.apispark.net1/v1/companies', form, {
    }).map(res => res.json());

I have an error when executing corresponding tests through gulp test.js (`ReferenceError: FormData is not defined`, same for the `Blob` type) but this work in browser...

**Comment by fxck** [comment]
merge incoming anytime soon @robwormald ?

**Comment by MarkoSulamagi** [comment]
Any updates? 

// This issue is not coming out of google really well. I spent around an hour trying to use Http service, before I found this issue in some stackoverflow post.

**Comment by mzhua** [comment]
@templth   The post method of the http only support string body now, if you want to use post method with formdata, i suggest you try this: First,set your header to "x-www-form-urlencoded". Second, set you body as : "test1=val1&test2=123456". But i also still don't how to upload file with angular http . Hope this would be helpful

**Comment by leosvelperez** [comment]
@robwormald any updates on adding support for ArrayBuffer, Blob?
any plans on merge [7260](https://github.com/angular/angular/pull/7260) any time soon?
we are needing this feature

**Comment by huyaxiong** [comment]
Hey,hows going?now i am using rc.1,meet the same problem.

**Comment by luciomr** [comment]
Hi, everyone! Any updates on this issue so far? Specifically the File upload support?

**Comment by fabricioferreira** [comment]
@luciomr, it seems that RC2 added support for many features around the http component, including WithCredentials and Content Type, where you can define the contents being of blob, file, etc.

I haven't had a chance to check it yet, as in my first try to upgrade from RC1 to RC2 presented a lot of issues.

**Comment by Krisa** [comment]
> it seems that RC2 added support for many features around the http component

I was also looking for the blob() method but I'm so far getting [this exception](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/static_response.ts#L92)

**Comment by dloukola** [comment]
I had to write my own using XHR. I couldn't wait for the angular team to
finish. When it comes in, I'll consider using the built in one.

On Saturday, 18 June 2016, Christophe Vidal <notifications@github.com>
wrote:

> it seems that RC2 added support for many features around the http component
>
> I was also looking for the blob() method but I'm so far getting this
> exception
> <https://github.com/angular/angular/blob/master/modules/%40angular/http/src/static_response.ts#L92>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/http/issues/75#issuecomment-226935358>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACsrGbgLEkHlXBqOHveblsppWexq3YChks5qM80PgaJpZM4HVzHM>
> .
>


-- 
Dave Loukola
613-261-4654

**Comment by luciomr** [comment]
> I had to write my own using XHR. I couldn't wait for the angular team to
finish.

Same here. But I want to use the built in alternative instead.

**Comment by fabricioferreira** [comment]
I'm currently using a hacked version of the http module, in order to support blobs and the withCredentials. In a week or two I'll give a try to the RC2 (I'm currently on RC1).

**Comment by huyaxiong** [comment]
FormData is support now,i test it in rc.3
Heres demo:
  var formData = new FormData(<HTMLFormElement>$('#entrustment-form')[0]);
        let headers = new Headers({'Content-Type': undefined});
        let options = new RequestOptions({
            headers: headers,
            processData: false,
            contentType: false
        });
        this._http.post(this._projectUrl, formData, options).subscribe(res => {
            console.log(res);
        });

**Comment by runtheyards** [comment]
My fix was to add the header `"content-type", "application/x-www-form-urlencoded"` and then re-purpose the `new URLSearchParams()` to convert and object into a url encoded string:

```
const urlEncodedBody = new URLSearchParams();
        for (let item in body) {
            urlEncodedBody.set(item, body[item]);
        }
```

**Comment by nosachamos** [comment]
It'd be great to have this for angular's upcoming 1.0 release.

**Comment by zoechi** [comment]
@nosachamos as far as I understand it, this is unrelated to Angular 1.0 release. The Http module will not be part of Angular2 core that will be released as 1.0, but instead versioned individually and maintained as an external module and will reach 1.0 later.

**Comment by nosachamos** [comment]
Yes, right, perhaps I expressed myself not too well. What I meant is that, whenever angular 2 reaches 1.0, a lot of people will start using it for larger and more complex apps, and in those file uploads tend to appear as a requirement more often than not. So even though the http module might not be at 1.0, it'd be great to support this (even if not in it's final form) before core is at 1.0.
